### PR TITLE
Added ability to set temperature unit to C or F to address Request #50

### PR DESCRIPTION
**Pull request by KK1L**
Added pulldown for temperature unit for Pi Status. G/Y/R warning bars are adjusted to match the unit. Temperature graph is cleared which a change in unit to have scale stay consistent.

### CODE REVIEW

**Comment by KK1L** [comment]
There is a weird thing with the label on the gauge not getting set to 'C' correctly every time. Working on it.

**Comment by KK1L** [comment]
Found the cause. Fixed. I committed the change to issue-50 branch. Not 100% sure this pull request gets that update or not. I am still working to fully understand the fork/branch/pull process.
Thanks for patience!

**Comment by kd9lsv** [comment]
@KK1L No worries. I am patient with this. Can you add here pictures of what you did (show before and after)? I probably need to create a template for Pull Request to help drive discussions/get the answers easier.

also feel free to update the title so that we can have better idea of what the pull request is.

**Comment by KK1L** [comment]
Pi Status tab changes
- Created a MUX to feed either F or C payload to the chart and gauge.
- Update the green/yellow/red ranges based on temperature unit
- Clear the chart whenever the unit is changed, so the scale matches and does not show false dramatic changes
image

Config tab change
-added  new subflow(?) to get existing temperature unit if any and set value for 1st use
-pulldown to choose C (Celcius) or F (Farenheit) and pass to global 'temperature_unit'
image

**Comment by kd9lsv** [comment]
Ron this post has the same changes as #51 I can help you out this evening if you would like it.

**Comment by KK1L** [comment]
made modification to the triggering of "Set Gauge Display Values" so the label is more stable.
image

**Comment by KK1L** [comment]
@kd9lsv I am getting the feel for the release process slowly. I can (or you can) blast #51 since it contains the same stuff. It is surely due to my misunderstanding the process. I created the pull from my root (?) fork (branch?) and updated that with the Pi Temp change as well they are both there. However the Issue-50 branch contains the latest update. Not sure how to have the updates I made in Issue-50 to be applied to my root fork. Maybe that will be automatic when/if the issue-50 branch is committed the the master at kylekrieg.

**Comment by kd9lsv** [comment]
the idea is that your master, matches the main master (the release environment). that way you can create different branches with individual fixes. it gives you an option on GitHub to fetch upstream, which allows for you to pull all changes to master to keep it synced with one button.

**Comment by kd9lsv** [comment]
I also want to let you know, the only thing that's changing is the solar data node not anything else. make sure to push any outstanding commits to the issue-50 branch.

**Comment by KK1L** [comment]
I have something wrong then I need to dig into. When I push branch issue-50 from node red I only see origin upstream options. Github terminology confuses me. I have to remind myself that fork, branch, push, pull are relative to the original source rather than from my point of view....among other things. I need to search for a basic git layout this is hiw it works overview.73 es God Bless de KK1L, Ron <><On Jan 20, 2023 18:08, Connor Dickey ***@***.***> wrote:
the idea is that your master, matches the main master (the release environment). that way you can create different branches with individual fixes. it gives you an option on GitHub to fetch upstream, which allows for you to pull all changes to master to keep it synced with one button.

**Comment by kd9lsv** [comment]
Origin is the forked repo (aka KK1L/Node-Red-Contesting-Dashboard) Upstream is the original/central one used (kylekrieg/Node-Red-Contesting-Dashboard)

Hope this picture helps explain a lot of it. 

I

**Comment by kd9lsv** [comment]
@KK1L The flow.json might not be commited yet in `issue-50`. If so, commit and push to issue-50. Once Github receives the commits (from the push) to [issue-50](https://github.com/KK1L/Node-Red-Contesting-Dashboard/tree/issue-50)  this will update the Pull Request.

image

**Pull request closed without merging**
